[versions]
agp = "8.13.2"
kotlin = "2.2.21"
appcompat = "1.7.1"
recyclerview = "1.4.0"
lifecycle = "2.9.4"
coroutines = "1.10.2"
jsoup = "1.21.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
